### PR TITLE
Add full Focal support

### PR DESCRIPTION
**Pull request by digitalsleuth**
Not sure just how open the BitCurator Consortium might feel about modernizing the Saltstack structure, and adding support for Focal, but I figured I'd ask.

The modifications made to this pull request add support for all applications through both Focal and Bionic, ensuring the user interface remains the same between the two (with the exception of the terminal, I took some liberties to customize the style based on the BitCurator colour scheme).

Additionally, it creates two formats for installation:
- Addon: allows for BitCurator states to be installed in an additional environment (SIFT / REMnux / m.a.t. / WSL) without impact to the desired structure of the user, and without modification to the user interface of graphical environment.
- Dedicated: allows for a complete installation, including themed customizations

I've also created Dockers for both Bionic and Focal (which I'm happy to add in an additional PR, I'm keeping this one separate to avoid confusion).

I'm also prepared to assist in the creation of a release structure and a CLI to pull down the release structure, similar to SIFT / REMnux / m.a.t., and assist with expansion into Jammy.

Hopefully you find this useful, but if not, no worries!

Cheers

### CODE REVIEW

**Comment by kamwoods** [comment]
Thanks for all of this! The Consortium is definitely interested in any help with LTS updates, improving the Saltstack config, and the other points you've addressed here. We could have a separate discussion with more context if warranted. For moving forward with this PR, I've tested in a fresh 20.04.4 VM and have a few comments:

1. The existing 18.04LTS-based build places .desktop files for various tools (packaged, compiled from source, scripts) in named folders on the desktop, and uses the script https://github.com/BitCurator/bitcurator-distro-salt/blob/main/bitcurator/env/usr/local/bin/launcher-trust.sh to set them trusted so they can be double-clicked and executed. This approach doesn't work in later releases, including 20.04LTS (for example, these .desktop files are unusable in the build based on this PR). Presenting these applications in clearly organized groups is useful for the BitCurator audience; it doesn't have to be .desktop files in folders on the actual desktop, but any updated approach should incorporate the existing grouping. I don't have a simple solution. Do you have any thoughts on how to handle this?

2. You have moved the bitcurator mounter scripts (https://github.com/BitCurator/bitcurator-distro-salt/tree/main/bitcurator/mounter) to an attic location. The bc_policyapp.py appindicator is a convenience in the 18.04LTS build to provide an icon in the top panel with menu items to enable/disable read-only mounting for USB devices. The safety issues and limitations of this script are documented in our guides, and keeping it would be useful. AFAICT it functions as desired in 20.04LTS along with our modified rbfstab. Can you clarify why you attic'd these?

3. We have a very basic installation script at https://github.com/bitcurator/bitcurator-distro-installer that pulls the most recent (or requested) tag from bitcurator-distro-salt and builds the environment. Future assistance in replacing this with something less primitive would be appreciated.

**Comment by digitalsleuth** [comment]
Hi @kamwoods , I'm glad to help out, and can address each of your points.

1. I do have a solution for the .desktop files, however I left them in on the off-chance that you might want/need them. There are a couple of different launchers I was looking at implementing which will allow these icons to be added to the launcher, keeping them readily available and organized, just not on the actual desktop.

2. The only reason I didn't keep the bc_policyapp appindicator was because the README in that folder states:
`These tools should be considered deprecated / no longer supported (see explanations below) and are retained only for legacy reference.` I do notice the icon in the VM and was unsure whether or not it was a remnant of previous installation, or put there intentionally. I have no problem adding that back to the installer, and keeping the icon there.
As for the rbfstab, I didn't attic it, as far as I can see it's still in the same location and hasn't been changed as part of the PR. Unless you're talking about the bc_mounter tool itself, then that falls under the same reasoning, because it had been declared as deprecated and unsupported. If you want them back, I have no problem putting them back in.

3. There are two methods by which the installer can be completed. The first is using nodejs to build a standalone binary to do this (already currently being done with SIFT, REMnux, and MAT). The second one is a new (not-yet-completed) tool called Cast by Erik Kristensen (https://github.com/ekristen/cast). It's still in Beta, but essentially it would be able to point at a GitHub repo which is designed to be installed using SaltStack, and install it straight from GitHub.

Hopefully this helps to answer your questions. If the launcher and installer ideas interest you, I'll do up some drafts of how they would look and let you know!

Cheers

**Comment by kamwoods** [comment]
Sorry for the delay. Yes, both the launcher and installer ideas would be helpful; we're also interested in the docker builds, of course, but in another PR is fine as you mentioned before. Additional comments:

1. We're open to different options for the launcher; the simplest option I could think of previously was simply to organize the launchers into folders under "Show Applications", but I didn't know at the time how to automate this. After a bit more reading (roughly based on the reply by mgoppold here https://forums.opensuse.org/showthread.php/504623-create-global-GNOME-app-folder-categories) I tested putting the .desktop files in the relevant spot (.local/share/applications or /usr/share/applications), adding system-db:site to /etc/dconf/profile/user, and adding the relevant app-folders entries to a new file at /etc/dconf/db/site.db/00_app_folder_defaults. I have a gist of what my test file looked like here: https://gist.github.com/kamwoods/18c667b1fecbc46b34a3b4d1d592e7b1. And of course running a dconf update. This worked well, with the caveat that the folders are mixed in among the existing launchers, rather than grouped together. Was something along these lines one of the methods you were considering?

2. That's my mistake. There was a point that those tools were going to be sunset, and then we got them updated and working again. I failed to update the README. Apologies - they should remain in.

3. I like the idea of Cast since it seems to good alternative to mild variants of the same installer proliferating across projects. Am I reading that right? But we're open to any practical solution that is stable and works now / in the near term.

**Comment by digitalsleuth** [comment]
Perfect, I'll submit the Dockerfiles in a separate PR, but they will likely have to come after the CLI and Release format PR (only because it's easier to build a thinner docker with the CLI and releases - you'll see what I mean once I do up the installer and release scripting).

1. The easiest way I've found to create the shortcuts is to create a .directory file and assigning the .desktop file to the Category of the directory file (a better example is https://github.com/digitalsleuth/mat-salt/tree/master/mat/theme/desktop/applications and you can see what's being done by looking at the .directory, .desktop, and init.sls files).

2. No problem getting those tools back into the mix, I'll add them back to the focal_compat PR.

3. Yes you read that right, Cast will proliferate across projects, allowing a single installer to install different projects, provided they all meet the same format. Right now, the PR focal_compat meets that format, but will need two more .yml files to be added (which I would add to the focal_compat PR).

The stable and 'works now' CLI is ready to go, but will require releases to be built, which can be done within seconds using a script which I will add to the focal_compat PR. Essentially the process is this:
- CLI (once built) will verify that Saltstack is installed and, if not, install it. Once installed, it will reach to GitHub to pull the latest release, unpack it, then install it via Salt (logging all steps along the way). 
- Releases are built by pushing changes to the repo, changing the VERSION number, then running a script to generate a release and push it to GitHub.
You can see this process via the [REMnux](https://github.com/remnux/remnux-cli), [SIFT](https://github.com/teamdfir/sift-cli), [m.a.t.](https://github.com/digitalsleuth/mat-cli), and [Win-FOR](https://github.com/digitalsleuth/winfor-salt) repos.

What I would like to do, if you're willing, is to add the .ci folder which will contain the scripts to create the releases. It will require that you add a GPG key to sign and hash the releases (you'll see in the script where to add the 8 character key). Once added, if you can merge the PR, then generate a release, I can create the CLI and test it against the release agent.

The other option for this is for me to create the CLI in a test repo, and create a second test repo which mirrors the changes I recommend in focal_compat so you can test it out.

**Comment by digitalsleuth** [comment]
So I decided to create the CLI and releases in separate repo's for testing (only takes a few minutes to do). You can go to https://github.com/digitalsleuth/bitcurator-cli to see the CLI, and it currently points to the releases at https://github.com/digitalsleuth/bitcurator-salt (notice it's not `distro`-salt, this is on purpose, for testing only).

You can download the CLI, move it to `/usr/local/bin/bitcurator` then `sudo chmod +x` and `sudo bitcurator install`. This will, by default install for the current user, as a dedicated installation (all themes and icons, etc). You can use `--mode`, `--user`, and `--version` to choose the mode of installation (addon/dedicated), the user for which you wish to install it (if not present, the user will be created), and the specific release of the salt states to be installed.

Let me know what you think if you get a chance to try it out.

**Comment by kamwoods** [comment]
Thanks! A note on a testing issue below, but first: I've made a new bitcurator-cli repo (https://github.com/bitcurator/bitcurator-cli) to host the installer if you're ok with sending a PR there. Note that there's no .gitignore in there yet. I'm also now considering leaving bitcurator-distro-salt as-is as a legacy repo for the 2.x and prior releases (to be retired as 18.04 reaches eol), and creating bitcurator-salt (matching your setup) to serve as the home for the new builds.This will provide myself and others a bit more leeway to update and transition legacy docs, links etc.

Small testing issue: I pulled down bitcurator-cli-linux v0.0.2, and in a fresh 20.04 vm logged in as the bcadmin user, copied it over to /usr/local/bin/bitcurator and ran it, but it failed out. Looking at the log, there seems to be an issue in line 8 of terminal.sls (user is Undefined). Tool output and relevant part of log below:

**Tool output:**
bcadmin@bitcurator:/usr/local/bin$ sudo ./bitcurator install
> bitcurator-cli@0.0.2.0.gbd878bb
> bitcurator-version: notinstalled

> downloading v3.0.4d
>> downloading bitcurator-salt-v3.0.4d.tar.gz.asc
>> downloading bitcurator-salt-v3.0.4d.tar.gz.sha256
>> downloading bitcurator-salt-v3.0.4d.tar.gz.sha256.asc
>> downloading bitcurator-salt-v3.0.4d.tar.gz
> validating file bitcurator-salt-v3.0.4d.tar.gz
> validating signature for bitcurator-salt-v3.0.4d.tar.gz.sha256
> extracting update bitcurator-salt-v3.0.4d.tar.gz
> no previous bitcurator version found; performing a new 'dedicated' installation.
> upgrading/updating to v3.0.4d
>> Log file: /var/cache/bitcurator/cli/v3.0.4d/saltstack.log

Update returned non-zero exit code
Error: Update returned non-zero exit code
    at ChildProcess.<anonymous> (/snapshot/bitcurator-cli/bitcurator-cli.js:547:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)


Try rebooting your system and trying the operation again.

Sometimes problems occur due to network or server issues when
downloading packages, in which case retrying your operation
a bit later might lead to good results.

To determine the nature of the issue, please review the
saltstack.log file under /var/cache/bitcurator/cli/ in the
subdirectory that matches the bitcurator version you're installing.
Pay particular attention to lines that start with [ERROR], or
which come before the line "result: false".


bcadmin@bitcurator:/usr/local/bin$ 

**Log:**
local:
- "Rendering SLS 'base:bitcurator.theme.terminal' failed: Problem running salt function
  in Jinja template: User 'undefined' is not available; line 8\n\n---\n[...]\n  {%
  set home = \"/root\" %}\n{% else %}\n  {% set home = \"/home/\" + user %}\n{% endif
  %}\n\n{% set dbus_address = salt['cmd.run'](\"dbus-launch | grep DBUS_SESSION_BUS_ADDRESS
  | cut -d= -f2-\", shell=\"/bin/bash\", runas=user, cwd=home, python_shell=True)
  %}    <======================\n\ninclude:\n  - bitcurator.config.user\n\nbitcurator-theme-terminal-profile-file:\n[...]\n---"

**Comment by digitalsleuth** [comment]
Yeah, that issue was a typo on my part. I'm not at a PC right now where I can fix it, but I'll get it done as soon as I get home. As for the rest, sounds good! I'll fix everything up and submit a PR to those repos as well!

**Comment by kamwoods** [comment]
Great, thank you! I've created bitcurator-salt (https://github.com/BitCurator/bitcurator-salt) as well. Will await the PRs there and at bitcurator-cli. I have a GPG key generated (and registered with pgp.mit.edu) and did see the places where 8-char goes in the script. Is there anything else I need to replace?

Is there a guide for (or would you mind briefly describing) the process of building/preparing-for-release the CLI itself? My nodejs experience is almost nil. I'd be doing this on a Ubuntu 22.04 box.

**Comment by digitalsleuth** [comment]
K, got the issue fixed in the CLI and in the terminal state. Both should work perfectly now.

I'll include the step-by-step in a markdown in the PR's so you can do the release for the states and release for the CLI when needed. The last thing will be to replace the GPG key in bitcurator-cli.js once I do the PR.

If you want to test the CLI and states now, the current CLI points to my bitcurator-salt. Ill update the CLI to accept 22.04 as an option as well, then will build locally for test, and modify the CLI to point to BitCurator/bitcurator-salt once you give me the word and do the PR.

**Comment by kamwoods** [comment]
Amazing, thank you! I'm running the build now in a fresh 20.04. Will get back to you shortly.

**Comment by digitalsleuth** [comment]
No worries. The current release does not have the launcher / shortcut options we discussed, though. My primary focus has been getting the CLI and release process done. Once you're happy with those, I'll PR what currently exists. Then I'll add the launcher / shortcut items we discussed and do a PR for those for the next release.

**Comment by kamwoods** [comment]
Thanks for the clarification. The build in 20.04 looks good to me / completed without error. It'll be great to have the 22.04 option as well.

**Comment by GeoffShortUoY** [comment]
I'm interested in 20.04 support - our staff are considering BitCurator but we would be very reluctant to install Ubuntu 18.04 at this late stage. I don't have much knowledge of the technologies here, but do have Ubuntu Desktop support experience and happy to run tests and give feedback.

**Comment by digitalsleuth** [comment]
Hi @GeoffShortUoY , the support for 20.04 and 22.04 is coming very soon, and will likely be handled at https://github.com/bitcurator/bitcurator-salt. A CLI installer is coming soon as well, so you should see something soon!

**Comment by kamwoods** [comment]
Closing this PR now. Future visitors: per the above comment from @digitalsleuth the updates discussed here (implementing 20.04 and 22.04 support) now live at https://github.com/bitcurator/bitcurator-salt and https://github.com/bitcurator/bitcurator-cli.

**Pull request closed without merging**
